# Generated by Django 2.0 on 2018-07-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('rua', models.CharField(max_length=40, verbose_name='Rua')),
                ('numero', models.CharField(max_length=10, verbose_name='Numero')),
                ('bairro', models.CharField(max_length=20, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=20, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'Enderecos',
                'verbose_name': 'Endereco',
                'ordering': ['estado', 'cidade', 'bairro'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=80, verbose_name='descricao')),
                ('endereco', models.ForeignKey(on_delete=False, to='unidade.Endereco')),
            ],
            options={
                'verbose_name_plural': 'Unidades',
                'verbose_name': 'Unidade',
                'ordering': ['nome', 'descricao'],
            },
        ),
    ]
