# Generated by Django 2.0 on 2018-07-31 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('matricula', models.CharField(max_length=11, unique=True, verbose_name='matricula')),
                ('turma', models.ForeignKey(blank=True, on_delete=False, to='turma.Turma')),
            ],
            options={
                'ordering': ['nome', 'matricula'],
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='AlunoSessao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.PositiveIntegerField(verbose_name='Média')),
                ('descricao_alterativas', models.CharField(blank=True, max_length=60, verbose_name='Descrição de Alterativas')),
                ('descricao_pontuacao', models.CharField(blank=True, max_length=60, verbose_name='Descrição de Pontuação')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.Aluno')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.Sessao')),
            ],
            options={
                'ordering': ['aluno', 'sessao', 'media'],
                'verbose_name': 'AlunoSessao',
                'verbose_name_plural': 'AlunosSessao',
            },
        ),
    ]
