# Generated by Django 2.0 on 2018-07-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('pontMax', models.PositiveIntegerField(verbose_name='Pontuação Máxima')),
                ('pontMin', models.PositiveIntegerField(verbose_name='Pontuação Mínima')),
                ('media', models.PositiveIntegerField(verbose_name='Média')),
            ],
            options={
                'verbose_name_plural': 'Questionarios',
                'verbose_name': 'Questionario',
                'ordering': ['nome', 'pontMin', 'pontMax', 'media'],
            },
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAplicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aplicação')),
                ('questionarios', models.ManyToManyField(to='turma.Questionario')),
            ],
            options={
                'verbose_name_plural': 'Sessoes',
                'verbose_name': 'Sessao',
                'ordering': ['pk', 'dataAplicacao'],
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=80, verbose_name='descricao')),
                ('data_referencia', models.DateField(blank=True, verbose_name='ano')),
                ('alunos', models.ManyToManyField(blank=True, to='aluno.Aluno')),
            ],
            options={
                'verbose_name_plural': 'Turmas',
                'verbose_name': 'Turma',
                'ordering': ['nome', 'descricao', 'data_referencia'],
            },
        ),
        migrations.AddField(
            model_name='sessao',
            name='turma',
            field=models.ForeignKey(on_delete=False, to='turma.Turma'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='turma.Topping'),
        ),
    ]
