# Generated by Django 2.0 on 2018-07-22 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('pontMax', models.PositiveIntegerField(verbose_name='Pontuação Máxima')),
                ('pontMin', models.PositiveIntegerField(verbose_name='Pontuação Mínima')),
                ('media', models.PositiveIntegerField(verbose_name='Média')),
                ('quantidade_questoes', models.PositiveIntegerField(verbose_name='Quantidade Questões')),
                ('descricao_alterativas', models.CharField(blank=True, max_length=60, verbose_name='Descrição de Alterativas')),
            ],
            options={
                'verbose_name_plural': 'Questionarios',
                'verbose_name': 'Questionario',
                'ordering': ['nome', 'pontMin', 'pontMax', 'media', 'quantidade_questoes'],
            },
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAplicacao', models.DateField(verbose_name='Data de Aplicação')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.Questionario')),
            ],
            options={
                'verbose_name_plural': 'Sessoes',
                'verbose_name': 'Sessao',
                'ordering': ['pk', 'dataAplicacao'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descricao')),
                ('data_referencia', models.DateField(blank=True, verbose_name='Data Referência')),
            ],
            options={
                'verbose_name_plural': 'Turmas',
                'verbose_name': 'Turma',
                'ordering': ['nome', 'descricao', 'data_referencia'],
            },
        ),
        migrations.AddField(
            model_name='sessao',
            name='turma',
            field=models.ForeignKey(on_delete=False, to='turma.Turma'),
        ),
    ]
