# Generated by Django 2.0 on 2018-07-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('pontMax', models.PositiveIntegerField(verbose_name='Pontuação Máxima')),
                ('pontMin', models.PositiveIntegerField(verbose_name='Pontuação Mínima')),
                ('media', models.PositiveIntegerField(verbose_name='Média')),
            ],
            options={
                'verbose_name': 'Questionario',
                'ordering': ['nome', 'pontMin', 'pontMax', 'media'],
                'verbose_name_plural': 'Questionarios',
            },
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAplicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aplicação')),
                ('questionarios', models.ManyToManyField(to='turma.Questionario')),
            ],
            options={
                'verbose_name': 'Sessao',
                'ordering': ['pk', 'dataAplicacao'],
                'verbose_name_plural': 'Sessoes',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=80, verbose_name='descricao')),
                ('data_referencia', models.DateField(blank=True, verbose_name='ano')),
            ],
            options={
                'verbose_name': 'Turma',
                'ordering': ['nome', 'descricao', 'data_referencia'],
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.AddField(
            model_name='sessao',
            name='turma',
            field=models.ForeignKey(on_delete=False, to='turma.Turma'),
        ),
    ]
