# Generated by Django 2.0 on 2018-06-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['nome', 'descricao', 'data_referencia'], 'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='ano',
            new_name='data_referencia',
        ),
    ]
