# Generated by Django 2.0 on 2018-06-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('pontMax', models.PositiveIntegerField(verbose_name='Pontuação Máxima')),
                ('pontMin', models.PositiveIntegerField(verbose_name='Pontuação Mínima')),
                ('media', models.PositiveIntegerField(verbose_name='Média')),
            ],
            options={
                'ordering': ['nome', 'pontMin', 'pontMax', 'media'],
                'verbose_name': 'Questionario',
                'verbose_name_plural': 'Questionarios',
            },
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAplicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aplicação')),
                ('alunos', models.ManyToManyField(to='turma.Aluno')),
                ('questionarios', models.ManyToManyField(to='turma.Questionario')),
            ],
            options={
                'ordering': ['pk', 'dataAplicacao'],
                'verbose_name': 'Sessao',
                'verbose_name_plural': 'Sessoes',
            },
        ),
    ]
