# Generated by Django 2.0 on 2018-06-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0002_questionario_sessao'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='sessoes',
            field=models.ManyToManyField(to='turma.Sessao'),
        ),
    ]
